version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/jar/
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root