version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: debug.sh
      timeout: 300
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 300
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 300