version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: debug.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root