version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/jar
hooks:
  BeforeInstall:
    - location: scripts/debug.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root