x-mysql-template: &mysql-template
  image: mysql:latest
  env_file:
    - .env.local
  healthcheck:
    test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    interval: 20s
    timeout: 10s
    retries: 3

services:
  mysql:
    <<: *mysql-template
    hostname: dev
    volumes:
      - ./db:/var/lib/mysql
    container_name: chat-db
    ports:
      - "3306:3306"
  memcached:
    container_name: solsol-memcached
    image: memcached:alpine
    ports:
      - 11211:11211